export { default as App } from "./App"
export { default as Home } from "./Home"
export { default as Projects } from "./Projects"
export { default as Contact } from "./Contact"
export { default as AboutMe } from "./AboutMe"